version: "3.7"

services:
  db:
    image: mariadb:10
    container_name: td-wp-db
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:5.5.1-fpm-alpine
    container_name: td-wp-site
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"

  nginx:
    image: nginx:1.15.12-alpine
    container_name: td-wp-nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - certbot-etc:/etc/letsencrypt

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: td-wp-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./wordpress:/var/www/html
        #command: certonly --webroot --webroot-path=/var/www/html --email fcaryv@gmail.com --agree-tos --no-eff-email --staging -d tdevelopments.ga -d www.tdevelopments.ga"
    command: certonly --webroot --webroot-path=/var/www/html --email fcaryv@gmail.com --agree-tos --no-eff-email --force-renewal -d tdevelopments.ga -d www.tdevelopments.ga

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: td-wp-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 10000000000

    

volumes:
  db: 
  certbot-etc:
